services:
  - type: worker
    name: moss-watcher
    runtime: docker
    dockerfilePath: ./Dockerfile.worker
    plan: free
    envVars:
      - key: DATABASE_URL
        value: postgres://e090abc9d5a5606d19ed67103590bcfe7537f3aeee775158608124218dcf93e0:sk_MXWjEBecCd0XpgUaKo9d2@db.prisma.io:5432/postgres?sslmode=require